import Header from "@/components/Header";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import React from "react";
import { Providers } from "@/Redux/provider";
export const metadata = {
  title: "Shopping App",
  description: "Generated by create next app",
};
const josefin = Josefin_Sans({ subsets: ["latin"] });
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/Footer";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={        josefin.className +
          " min-h-screen flex flex-col relative bg-gray-800 text-white"
}
      >

    <Header />
    <div className="flex-1 px-8 py-12">
      <main className="max-w-7xl mx-auto">
        <ToastContainer position="bottom-right" autoClose={2000} />
      <Providers>{children}</Providers>
      </main>
    </div>
  <Footer/>
      
         </body>
    </html>
  );
}
