import UpdateProfileForm from '@/components/updatePofileform'
import React from 'react'
export const metadata = {
  title: "profile",
  description: "Generated by create next app",
};

export default function Profile() {
  return (
    <div>
        <h2 className='font-semibold text-2xl text-accent-400 mb-2'>
            Update your guest profile
        </h2>
        <p className='"text-lg mb-2 text-primary-200'>
            Provider the following information will make your check-in process
        </p>
        <UpdateProfileForm/>
    </div>
  )
}
